give  Sun 30 Jun 22:24:36 AEST 2019: something is still broken

diff --git a/legit-show b/legit-show
--- a/legit-show
+++ b/legit-show
@@ -22,11 +22,12 @@ commit=$(echo "$1" | cut -d':' -f1)
 if [ -z $commit ]; then
 
 	if [ ! -f .legit/index/$file ]; then
-	echo "$filename: error: '"$file"' not found in index"
-	exit 1
-else
-	cat .legit/commit/commit_$commit/$file
-	exit 1
+		echo "$filename: error: '"$file"' not found in index"
+		exit 1
+	else
+		cat .legit/commit/commit_$commit/$file
+		exit 1
+	fi
 fi
 			
 file=$(echo "$1" | cut -d':' -f2)
