give  Fri 28 Jun 11:07:36 AEST 2019: Fixed bug with not checking if legitinit has been executed

diff --git a/legit-add b/legit-add
--- a/legit-add
+++ b/legit-add
@@ -2,6 +2,10 @@
 
 filename="`echo "$0" | rev | cut -d'/' -f1 | rev `"
 
+if [ ! -d ".legit" ]; then
+	echo "$filename: error: no .legit directory containing legit repository exists"
+	exit 1
+fi
 if [ $# -eq 0 ]; then
 	echo "usage: "$filename" <filenames>" 
 	exit 1
