give  Sun 30 Jun 22:23:32 AEST 2019: i think i broke something

diff --git a/legit-show b/legit-show
--- a/legit-show
+++ b/legit-show
@@ -18,6 +18,17 @@ if [ -z "$check" ]; then
 	exit 1
 fi
 commit=$(echo "$1" | cut -d':' -f1)
+
+if [ -z $commit ]; then
+
+	if [ ! -f .legit/index/$file ]; then
+	echo "$filename: error: '"$file"' not found in index"
+	exit 1
+else
+	cat .legit/commit/commit_$commit/$file
+	exit 1
+fi
+			
 file=$(echo "$1" | cut -d':' -f2)
 check=$(cat .legit/commit/commit_history.txt | egrep "commit $commit")
 if [ -z "$check" ]; then
