give  Thu 11 Jul 22:23:49 AEST 2019: Stderr

diff --git a/legit-add b/legit-add
--- a/legit-add
+++ b/legit-add
@@ -3,12 +3,12 @@
 filename="`echo "$0" | rev | cut -d'/' -f1 | rev `"
 
 if [ ! -d ".legit" ]; then
-	echo "$filename: error: no .legit directory containing legit repository exists"
+	echo "$filename: error: no .legit directory containing legit repository exists" >&2
 	exit 1
 fi
 branch=`cat .legit/current_branch`
 if [ $# -eq 0 ]; then
-	echo "usage: "$filename" <filenames>" 
+	echo "usage: "$filename" <filenames>" >&2
 	exit 1
 fi 
 
@@ -17,7 +17,7 @@ do
 	files=$(echo "$file" | egrep "[^a-zA-Z0-9._-]")	
 	#echo $files	
 	if [ ! -z $files ]; then	
-		echo ""$filename": error: invalid filename '"$file"'"
+		echo ""$filename": error: invalid filename '"$file"'" >&2
 		exit 1
 	fi
 done
@@ -31,7 +31,7 @@ do
 		if [ -f ".legit/"$branch"/add/"$file"" ]; then
 			rm .legit/"$branch"/add/"$file"
 		else	 			
-			echo ""$filename": error: can not open '"$file"'"
+			echo ""$filename": error: can not open '"$file"'" >&2
 			exit 1
 		fi
 	fi
diff --git a/legit-commit b/legit-commit
--- a/legit-commit
+++ b/legit-commit
@@ -3,19 +3,19 @@
 filename="`echo "$0" | rev | cut -d'/' -f1 | rev `"
 
 if [ ! -d ".legit" ]; then
-	echo "$filename: error: no .legit directory containing legit repository exists"
+	echo "$filename: error: no .legit directory containing legit repository exists" >&2
 	exit 1
 fi
 branch=`cat .legit/current_branch`
 if [ $# -le 1 ]; then
-	echo "usage: "$filename" [-a] -m commit-message" 
+	echo "usage: "$filename" [-a] -m commit-message" >&2 
 	exit 1
 
 elif [ $# -eq 3 ]  && ( [ $1  != "-a" ] || [ ! $2  = "-m" ] ) ; then
-	echo "usage: "$filename" [-a] -m commit-message" 
+	echo "usage: "$filename" [-a] -m commit-message" >&2
 	exit 1
 elif [ $# -eq 2 ]  && [ $1  != "-m" ]; then
-	echo "usage: "$filename" [-a] -m commit-message" 
+	echo "usage: "$filename" [-a] -m commit-message" >&2
 	exit 1
 fi
 
@@ -47,7 +47,7 @@ else
 fi
 
 if [ -z "$commitmessage" ]; then
-	echo "usage: "$filename" [-a] -m commit-message" 
+	echo "usage: "$filename" [-a] -m commit-message" >&2
 	exit 1
 fi
 
@@ -56,11 +56,11 @@ if [ $commit -ge 0 ]; then
 	testvariable=$(diff .legit/"$branch"/commit/"$dir" .legit/"$branch"/add ) 	
 	if [ -z  "$testvariable" ]; then
 		echo "nothing to commit"
-		exit 1	
+		exit 0	
 	fi
 elif [ -z "$(ls -A .legit/"$branch"/add)" ]; then
 	echo "nothing to commit"
-	exit 1 
+	exit 0 
 fi
 commit=$(( commit+1 ))
 
diff --git a/legit-init b/legit-init
--- a/legit-init
+++ b/legit-init
@@ -3,11 +3,11 @@
 filename="`echo "$0" | rev | cut -d'/' -f1 | rev `"
 
 if [ $# -ne 0 ]; then
-	echo "usage: "$filename"" 
+	echo "usage: "$filename"" >&2
 	exit 1
 elif [ -d ".legit" ]; then
 
-	echo "$filename: error: .legit already exists"
+	echo "$filename: error: .legit already exists" >&2
 	exit 1
 fi
 mkdir -p ".legit/master/commit"
diff --git a/legit-log b/legit-log
--- a/legit-log
+++ b/legit-log
@@ -3,15 +3,15 @@
 filename="`echo "$0" | rev | cut -d'/' -f1 | rev `"
 
 if [ ! -d ".legit" ]; then
-	echo "$filename: error: no .legit directory containing legit repository exists"
+	echo "$filename: error: no .legit directory containing legit repository exists" >&2
 	exit 1
 fi
 branch=`cat .legit/current_branch`
 if [ -z "$(ls -A .legit/"$branch"/commit)" ]; then
-	echo "$filename: error: your repository does not have any commits yet"
+	echo "$filename: error: your repository does not have any commits yet" >&2
 	exit 1
 elif [ $# -ne 0 ]; then
-	echo "usage: "$filename"" 
+	echo "usage: "$filename"" >&2 
 	exit 1
 else
 	cat .legit/"$branch"/commit/commit_history.txt | cut -d' ' --complement -f1 | sort -r
diff --git a/legit-rm b/legit-rm
--- a/legit-rm
+++ b/legit-rm
@@ -3,15 +3,15 @@
 filename="`echo "$0" | rev | cut -d'/' -f1 | rev `"
 
 if [ ! -d ".legit" ]; then
-    echo "$filename: error: no .legit directory containing legit repository exists"
+    echo "$filename: error: no .legit directory containing legit repository exists" >&2
     exit 1
 fi
 branch=`cat .legit/current_branch`
 if [ -z "$(ls -A .legit/"$branch"/commit)" ]; then
-    echo "$filename: error: your repository does not have any commits yet"
+    echo "$filename: error: your repository does not have any commits yet" >&2
     exit 1
 elif [ $# -lt 1  ]; then
-    echo "usage: "$filename" [--force] [--cached] <filenames>"
+    echo "usage: "$filename" [--force] [--cached] <filenames>" >&2
     exit 1
 fi
 
@@ -27,7 +27,7 @@ while [ ! -z $arg ]; do
     elif [ $arg = "--cached" ]; then
         cached=1;
     else    
-        echo "usage: "$filename" [--force] [--cached] <filenames>"
+        echo "usage: "$filename" [--force] [--cached] <filenames>" >&2
         exit 1
     fi      
     shift
@@ -35,7 +35,7 @@ while [ ! -z $arg ]; do
 done
 
 if [ $# -eq 0 ]; then
-    echo "usage: "$filename" [--force] [--cached] <filenames>"
+    echo "usage: "$filename" [--force] [--cached] <filenames>" >&2
     exit 1
 fi
 #echo "$commit zis is ze commit cache $cached forced $forced"
@@ -43,12 +43,12 @@ for file in "$@"; do
     #echo $file	
     arg=`echo "$file" | grep ^--`
     if [ ! -z $arg ]; then
-        echo "usage: "$filename" [--force] [--cached] <filenames>"
+        echo "usage: "$filename" [--force] [--cached] <filenames>" >&2
         exit 1
     fi
     
     if [ ! -f ".legit/"$branch"/add/"$file"" ]; then
-	echo "$filename: error: '"$file"' is not in the legit repository"
+	echo "$filename: error: '"$file"' is not in the legit repository" >&2
 	exit 1
     else 
 	if [ $forced -eq 1 ]; then
@@ -65,7 +65,7 @@ for file in "$@"; do
 			rm -f .legit/"$branch"/add/"$file"
 			continue		
 		elif ([ -f .legit/"$branch"/add/"$file" ] && [ ! -f .legit/"$branch"/commit/commit_$commit/"$file" ]) || [ -n "$(diff -q .legit/"$branch"/add/"$file" .legit/"$branch"/commit/commit_$commit/"$file")" ]; then
-			echo "$filename: error: '"$file"' has changes staged in the index"
+			echo "$filename: error: '"$file"' has changes staged in the index" >&2
 			exit 1
 		fi
 		
@@ -80,10 +80,10 @@ for file in "$@"; do
 				rm -f .legit/"$branch"/add/"$file"	
 				continue
 			fi
-			echo "$filename: error: '"$file"' in repository is different to working file"
+			echo "$filename: error: '"$file"' in repository is different to working file" >&2
 			exit 1
 		else
-			echo "$filename: error: '"$file"' in index is different to both working file and repository"
+			echo "$filename: error: '"$file"' in index is different to both working file and repository" >&2
 			exit 1
 		fi		
 	fi		
diff --git a/legit-show b/legit-show
--- a/legit-show
+++ b/legit-show
@@ -3,21 +3,21 @@
 filename="`echo "$0" | rev | cut -d'/' -f1 | rev `"
 
 if [ ! -d ".legit" ]; then
-	echo "$filename: error: no .legit directory containing legit repository exists"
+	echo "$filename: error: no .legit directory containing legit repository exists" >&2
 	exit 1
 fi
 branch=`cat .legit/current_branch`
 if [ -z "$(ls -A .legit/"$branch"/commit)" ]; then
-	echo "$filename: error: your repository does not have any commits yet"
+	echo "$filename: error: your repository does not have any commits yet" >&2
 	exit 1
 elif [ $# -ne 1 ]; then
-	echo "usage: $filename <commit>:<filename>"
+	echo "usage: $filename <commit>:<filename>" >&2
 	exit 1
 fi
 
 check=$(echo "$1" | egrep ":")
 if [ -z "$check" ]; then
-	echo "$filename: error: invalid object "$1""	
+	echo "$filename: error: invalid object "$1"" >&2	
 	exit 1
 fi
 commit=$(echo "$1" | cut -d':' -f1)
@@ -25,7 +25,7 @@ file=$(echo "$1" | cut -d':' -f2)
 if [ -z $commit ]; then
 
 	if [ ! -f .legit/"$branch"/add/"$file" ]; then
-		echo "$filename: error: '"$file"' not found in index"
+		echo "$filename: error: '"$file"' not found in index" >&2
 		exit 1
 	else
 		cat .legit/"$branch"/add/"$file"
@@ -36,10 +36,10 @@ fi
 
 check=$(cat .legit/"$branch"/commit/commit_history.txt | egrep "commit $commit")
 if [ -z "$check" ]; then
-	echo "$filename: error: unknown commit '$commit'"
+	echo "$filename: error: unknown commit '$commit'" >&2
 	exit 1
 elif [ ! -f .legit/"$branch"/commit/commit_$commit/"$file" ]; then
-	echo "$filename: error: '"$file"' not found in commit $commit"
+	echo "$filename: error: '"$file"' not found in commit $commit" >&2
 	exit 1
 else
 	cat .legit/"$branch"/commit/commit_$commit/"$file"
diff --git a/legit-status b/legit-status
--- a/legit-status
+++ b/legit-status
@@ -3,12 +3,12 @@
 filename="`echo "$0" | rev | cut -d'/' -f1 | rev `"
 
 if [ ! -d ".legit" ]; then
-    echo "$filename: error: no .legit directory containing legit repository exists"
+    echo "$filename: error: no .legit directory containing legit repository exists" >&2
     exit 1
 fi
 branch=`cat .legit/current_branch`
 if [ -z "$(ls -A .legit/"$branch"/commit)" ]; then
-    echo "$filename: error: your repository does not have any commits yet"
+    echo "$filename: error: your repository does not have any commits yet" >&2
     exit 1
 fi
 
